### ISSUE TITLE
yalc use custom global directory for package storage via environment variable

### ISSUE THREAD

**Issue by hyperupcall** [wclr/yalc#135]
by default, packages are stored at `~/.yalc`. i think it would be very useful to have the option to change it - would it be possible to introduce some global environment variable to customize this behavior? i'm thinking something like `YALC_PACKAGES_FOLDER` could suffice because it has a [similar name](https://github.com/whitecolor/yalc/blob/6fc6847b566fd10467fc674455a31c88f2ea1ab2/src/index.ts#L13). if the feature looks as simple as this, i can create a pr for this feature

edwin

**Comment by nicklas-delphai** [comment]
It also would be nice if `yalc` would adhere to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
