### ISSUE TITLE
Publish does not resolve workspace:

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [wclr/yalc#148]
I want to yalc to publish a package from a monorepo so that it can be used in another repository.

The package.json in `<monorepo>/packages/foo` has workspace dependencies

```
{
  "name": "@my-scope/foo",
  "version": "1.0.0",
  "dependencies": {
    "@my-scope/bar": "workspace:*"
  }
}
```

When I run `yalc publish` on `<monorepo>/packages/foo` it creates a tarball but the package.json inside of it still has this dependency.

```
  "dependencies": {
    "@my-scope/bar": "workspace:*"
  }
```

So any operation like `npm/yarn/pnpm update` in the external pacakge will fail after having added `@my-scope/foo` because the external package will try to resolve the dependency `@my-scope/bar` in its local workspace which it cannot find.

I expected yalc to behave like `pnpm publish` and replace workspace dependency versions. Yalc should locate the path to the project `@my-scope/bar`, read its `package.json#version` (1.0.0) and replace it inside the tarball.

```
  "dependencies": {
      "@my-scope/bar": "1.0.0"
  }
```

Perhaps having full `workspace:` resolution is too complex to implement unless this task is delegated to the package manager. Then, what if yalc implemented a simple workaround?

```ts
const modPackageDev = (pkg: PackageManifest) => {
  let newDependencies: undefined | object;
  
  if (pkg.dependencies) {
    newDependencies = {};
    Object.entries(pkg.dependencies).forEach(([name, version]) => {
      newDependencies[name] = version.replace(/^workspace:/, '')
    })
  }
  
  return {
    ...pkg,
    scripts: pkg.scripts
      ? {
          ...pkg.scripts,
          prepare: undefined,
          prepublish: undefined,
        }
      : undefined,
    devDependencies: undefined,
    dependencies: newDependencies
  }
}
```

It's not perfect, `"@my-scope/bar": "workspace:*"` resolves to `"*"` instead of `"1.0.0"` but it makes npm/yarn/pnpm happy.

`workspace:*` -> `*`
`workspace:^1.2.3` -> `^1.2.3`

Then you can use yalc as follows

```bash
# In @my-scope/foo
yalc publish
cd <external-project>
yalc link @my-scope/foo
npm update # works!!!
```

**Comment by whitecolor** [comment]
Well, I don't think that `yalc` not going to resolve anything, ect. Yalc is very simple tool. An the other reason that yalc is trying to mimic publish workflow to npm registry. Are you going to publish there with workspace deps too? Well it may be the option, if you assume that target project will be a workspace having dep package.

So I can recommend placing workspace dep in `depDependencies`, and versioned dep to `dependencies`. It should work I believe, at least I do it this way in my projects.

**Comment by javier-garcia-meteologica** [comment]
> Are you going to publish there with workspace deps too?

This is how pnpm works, you declare workspace dependencies and when you run `pnpm publish` workspace dependencies are resolved by pnpm.

https://pnpm.js.org/en/workspaces#publishing-workspace-packages

In my case, we have a monorepo of multiple packages that have dependencies among. If I didn't use the workspace protocol and instead used regular versioned dependencies, they would be downloaded from the registry instead of being built locally. Using `workspace:*` helps us automating the versioning of published versions and at the same time allows us to use local dependencies in development within the repo.

**Comment by whitecolor** [comment]
I didn't know about the publishing capabilities of pnpm, then I belive this could be implemented in yalc. I believe simple `require.resolve` would work for resolving.
