### ISSUE TITLE
how to correctly `npm publish`?

### ISSUE THREAD

**Issue by loveencounterflow** [wclr/yalc#149]
I'm developing a module that is going to be published with `npm publish`. I just found out that when I do `npm install $myproject` the installation is incorrect because it contains broken symlinks in the `node_modules` folder that point to the dependencies as `$myproject/.yalc/$dependency`. 

IMHO the correct way would be to have everything installed as if I hadn't used yalc at all (i.e. yalc acts as a transparent development assistant). Of course this leaves open the question which version of the dependencies to enter in `package.json`, but one could still throw an error if any yalc'ed dependency is not published with npm in its most recent version.

**Comment by wclr** [comment]
How are you adding dependency with `yalc add` or yalc link? Do you include `.yalc/dependency` in npm package?

**Comment by loveencounterflow** [comment]
I'm using `yalc add` as I had an error using `yalc link` (would have to retry to give more detail).

> Do you include .yalc/dependency in npm package?

No which is the reason it's not present when the module gets `npm install`ed. The reason it'*s not included in the package is of course because `.yalc` gets mentioned in `.gitignore` which is inherited by `npm`. I *could* certainly write an `.npmignore` that does not exclude the `.yalc` folder but is that really how things are supposed to work? I mean consumers of `$myproject` normally expect to get semantically-versioned transitive dependencies (as with all packages that are installed via `npm`), not the snapshots that yalc provides. 

The way it looks to me right now is I'd have to tear down all that yalc stuff and re-install dependencies in `$myproject` prior to publishing to `npm`. This is somewhat feasible and certainly scriptable but it still doesn't sound or feel right.

**Comment by wclr** [comment]
> This is somewhat feasible and certainly scriptable but it still doesn't sound or feel right.

Yalc has the command `yalc retreat` which replaces versions from `yalc.lock` to package.json.

so in package.json scripts:
```json
  "release": `yalc retreat --all && npm pubilsh` // will replace `file:yalc` with saved versions from `yalc.lock` prior publishing
  "postpublish": `yalc update` // will bring back `file:.yalc/` package back
```

Didn't test it for your case and report back. 

I need to add `retreat` docs, not sure why it is not there. Maybe also need to add the `restore` command because `update` will try pull the latest version from yalc store and fails if it is not there, which actually should not be an issue for most cases.

**Comment by loveencounterflow** [comment]
Ah OK that sounds like it would solve my problem there. Definitely put it in the docs tho. May I suggest to make it an option to add those hooks to `package.json` and also add `.yarn` to `.gitignore`?

Somewhat related but maybe worthy of a separate issue: I think there are two valid ways to link to a given dependency—one would be to the currently published version in `~/.yalc`, the other to the actual folder of that dependency. The second way is basically what `npm link` does but yalc could do it without the downsides of `npm link` (which magically vanishes whenever one does any `npm install xy` and so on).

**Comment by wclr** [comment]
> May I suggest to make it an option to add those hooks to package.json and also add .yarn to .gitignore?

Not sure what you mean.

**Comment by loveencounterflow** [comment]
I wanted to suggest to perform those changes to `package.json` and `.gitignore` as part of running a `yalc` command such as `yalc add`. I guess that would be another issue though so I'm closing this one.
