### ISSUE TITLE
`yalc publish` diverges from `yarn pack` behavior

### ISSUE THREAD

**Issue by jessemyers** [wclr/yalc#161]
I've created an example repo that demonstrates the issue [here](https://github.com/jessemyers/yalc-debug).

For context, we use (and love) `yalc` for library development and recently noticed that some of our libraries are not properly published. Our libraries are TypeScript and include a `yarn build` step that generates compiled files in a `dist` directory. We have our `package.json` configured to publish the contents of the `dist` directory and `yarn package` indicates that the expected files are included when we publish the library.

The example repo simulates this behavior by copying two files into the `dist` directory (no need for TypeScript to demonstrate the issue). One of these files is source (`src/index.js`) and one is the `package.json`. The latter file appears to confuse `yalc`, which diverges from the `yarn pack` behavior by _only_ including `dist/package.json` in its published files, ignoring `dist/index.js`. This happens regardless of the source structure that we create within the `dist` directory.

**Comment by wclr** [comment]
I've update `npm-packlist` and it seems to fix the issue. The new version is published.

**Comment by jessemyers** [comment]
Looks better, thank you for the quick turn around:

```sh
$ yalc --version
1.0.0-pre.51

$ yalc publish --files
Files included in published content:
- LICENSE
- dist/index.js
- dist/src/index.js
- dist/package.json
- package.json
- README.md
Total 6 files.
```
