### ISSUE TITLE
Add support for "workspace:^" and "workspace:~"

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [wclr/yalc#162]
The workspace protocol has 2 new specifications named `workspace:^` and `workspace:~`.

They are [already supported in pnpm](https://github.com/pnpm/pnpm/issues/3116) and will supported by [yarn in the near future](https://github.com/yarnpkg/berry/issues/2658).

**Comment by wclr** [comment]
@javier-garcia-meteologica 
Could you explain what is current behaviour/scenario and how this change will update it?

**Comment by javier-garcia-meteologica** [comment]
In a monorepo contains the following packages.

- `my-package@1.0.0`
- `foo@0.9.1`
- `bar@2.3.4`
- `another-package@1.2.3`

There is a package with workspace dependencies.

```json
{
  "name": "my-package",
  "version": "1.0.0",
  "dependencies": {
    "foo": "workspace:*",
    "bar": "workspace:^",
    "another-pkg": "workspace:~"
  }
```

Workspace dependency specifications only work within the monorepo. They have to be substituted when the project is packaged. `pnpm` and `yarn` would take care of this task but yalc doesn't invoke them. So if yalc packs the project  it has to resolve those workspace version aliases and publish the following manifest.

```json
{
  "name": "my-package",
  "dependencies": {
    "foo": "0.9.1",
    "bar": "^2.3.4",
    "another-pkg": "~1.2.3"
  }
```

**Comment by wclr** [comment]
Ok, get it.
