### ISSUE TITLE
Linking with own dependencies

### ISSUE THREAD

**Issue by lublak** [wclr/yalc#174]
I currently have a module (1) with jsonata as a dependency.
I then publish this module in the store of yalc.
The node_modules are then not copied with makes sense since yalc itself acts as a store like npm.
But now I use yalc add to link my own module (1), with the other module (2).
Now the dependency of jsonata is missing. It is neither in the .yalc folder of the second module (2), nor in the store, nor anywhere else.
Is this function wanted and if so is there an option to copy/install the dependencies like jsonata with it?

**Comment by wclr** [comment]
I think it still not possible to install deps automatically when using `yalc link`
So you have two options:

1) add those deps in the parent package
2) install manually running package manager installer inside `.yalc/your-package`

another way it to use `yalc add`

**Comment by lublak** [comment]
@wclr thanks for the answer, i now just copy node_modules manually to .yalc.
