### ISSUE TITLE
yalc update  + vite

### ISSUE THREAD

**Issue by huanyue2019** [wclr/yalc#189]

**Comment by huanyue2019** [comment]
在所开发的依赖项目已执行发布操作，另一个项目使用中执行yalc update依赖没有更新。

执行` rm -rf node_modules/.vite `版本更新一直滞后，甚至不更新。

**Comment by Tate-Young** [comment]
@huanyue2019 然后呢，我也遇到这个问题。目前通过 vite 插件是可以实时监听，但是改不了 .vite cache，需要手动清除，这样就比较麻烦。

**Comment by wztlink1013** [comment]
@Tate-Young @huanyue2019 大佬们，除了对.vite文件夹手动清除操作，还有别的放的方法来解决这个问题吗？

**Comment by DorothyGuan** [comment]
启动时加--force参数，或者force参数配置在config文件里面（我用这个方法可行），参见：https://cn.vitejs.dev/guide/dep-pre-bundling.html#caching

**Comment by leslie-choi** [comment]
> 启动时加--force参数，或者force参数配置在config文件里面（我用这个方法可行），参见：https://cn.vitejs.dev/guide/dep-pre-bundling.html#caching

加上 force 参数 但是好像还是要重启项目才会生效 还有没有啥更好的方法呢

**Comment by Tate-Young** [comment]
@wztlink1013 @leslie-choi 撸一个 vite 插件，去监听 .yalc 变化，然后重新预编译

**Comment by cccnobody** [comment]
> 在所开发的依赖项目已执行发布操作，另一个项目使用中执行yalc update依赖没有更新。
> 
> 执行`rm -rf node_modules/.vite`版本更新一直滞后，甚至不更新。

试试看这个插件呢。https://github.sheincorp.cn/cccnobody/vite-plugin-watch-and-restart/tree/main

**Comment by LiMao00** [comment]
> > 在所开发的依赖项目已执行发布操作，另一个项目使用中执行yalc update依赖没有更新。
> > 执行`rm -rf node_modules/.vite`版本更新一直滞后，甚至不更新。
> 
> 试试看这个插件呢。https://github.sheincorp.cn/cccnobody/vite-plugin-watch-and-restart/tree/main

试用了你的插件，内容变动时重新启动了很多很多次，应该有 bug
