### ISSUE TITLE
[Question] Can I use yalc in a "permanent" manner within a monorepo?

### ISSUE THREAD

**Issue by ctrlplusb** [wclr/yalc#194]
Love this lib, thank you!

I'm on a journey to create a monorepo that does not utilise any workspaces or hoisting features. Masochist, maybe? 😅 Long story, but I am over hoisting related issues.

I'd love to use `yalc` to help me manage cross package dependencies within my monorepo. I feel like yalc isn't really described for this case, in which it would be a "permanent" feature of the monorepo, rather than a temporary dev related workaround.

I've got it working, but my workflow needs to be ironed out a bit. 

Has anyone else had experience in this respect? How do you enable seamless clones of a monorepo in which `yalc` is managing the cross dependencies? Do you commit `yalc.lock` files, and how do you rehydrate the store etc? I'm also interested in hearing about any consideration to make the push of updates more seamless.

Thanks ya'll. ♥️

**Comment by wclr** [comment]
In most cases I commit yalced packages into git. So, I use yalc as a way to install some "permanent" stuff in (usually monorepo) projects, the stuff that is managed by me, that is in dev mode and not published for a shared consumption.

**Comment by ctrlplusb** [comment]
> For using packages across a monorepo I use workspaces feature. Yalc is for installing external stuff.

Yeah, I'm explicitly trying to avoid workspaces. I don't want to leverage hoisting. My goal is to try to enable monorepo style development whilst utilising yalc to manage the dependencies between the packages of the monorepo.

**Comment by ctrlplusb** [comment]
@wclr - I'm riffing on some ideas for a complementary CLI on top of yours, which is specific to my usecase. I've riffed out the readme for this theoretical package;

https://github.com/ctrlplusb/yalcd

What do you think? Any concerns or objections?

**Comment by wclr** [comment]
> Yeah, I'm explicitly trying to avoid workspaces. I don't want to leverage hoisting.

What is the real problem with workspaces/hoisting? I usually use [PNPM](https://pnpm.io/) for managing monorepos.

**Comment by robgraeber** [comment]
@ctrlplusb It's pretty easy getting yalc to working sustainably for a monorepo. 

For example I have a postinstall script setup:
```
"scripts": {
    "postinstall": "yarn workspaces foreach exec yalc publish --push",
  },
```
Then you `yalc add` in the projects you need it in and commit the yalc.lock file and ignore the .yalc folder.

Now whenever you make a change in a sibling package you would `yarn` to propagate the change.

**Comment by robgraeber** [comment]
@wclr workspace symlinks/hoisting aren't great because often times multiple versions of a library can't coexist together. For example I have a monorepo package that has React as a dev dependency but Yarn workspace will symlink along the node_modules folder too when I use the package elsewhere and that causes all kinds of problems.

**Comment by justsaul** [comment]
Although issue is resolved, i would just like to add to @robgraeber comment. I'm dealing with same issue - devDependencies. This is really painful in yarn workspaces. Ideally, yes, you would sync dependencies, however that is not feasible in big monorepos that may contain multiple packages.
