### ISSUE TITLE
Why node_modules isn't linked in?

### ISSUE THREAD

**Issue by adi518** [wclr/yalc#87]
When I add a local package with `yalc`, it links everything but leaves out `node_modules`. I'm guessing it's by-design, but it means I can't spawn a binary file, because `node_modules` simply isn't there. If I try to use `./bin`, I collide into cross-platform issues (works in Linux, fails on Windows, etc').

**Comment by whitecolor** [comment]
Not sure what you are trying to do. What command do you use?

**Comment by adi518** [comment]
`yalc publish` and then `yalc add my-package`. I eventually realized it does add my package `node_modules`, only they are "hoisted" or added to the main package `node_modules`. I managed to spawn the binary I needed by using a relative path, so I guess it's fine. 👍

**Comment by bramski** [comment]
I am having the opposite problem. My yalc installed package includes it's `/node_modules` and I do not want that. How can I get yalc not to include `node_modules`? Our package is rolled up and shouldn't have any included dependencies.

**Comment by adi518** [comment]
I stopped using Yalc since Yarn workspaces. The latter allows you to consume local packages with ease, you just place them in your workspaces directory and hit install. The rest is done for you, and when developing a package and watching for changes, it will trigger a new build in the consuming application. I think not many are aware of these amazing capabilities which have saved me what would be otherwise countless hours. In one instance, I was working on integrating six local packages into an application. That would have been a nightmare with Yalc.

**Comment by wclr** [comment]
> place them in your workspaces directory

So your workspace now pointing to outside of the project, it is something like `yarn/npm link`. Yalc allows you to be decoupled from your local environment and be more consistent. If you need things like watching, etc, yalc is not for that kind of workflow.

**Comment by wclr** [comment]
> I am having the opposite problem. My yalc installed package includes it's /node_modules 

Yalc by default grabs the same content as npm would grab for publishing.

**Comment by adi518** [comment]
@wclr I realized that. Btw, using workspaces doesn't mean you have to incorporate workspaces into a repository and version control. You simply create a local root workspace and clone what you need inside it.

I'm trying to figure out use-cases for yalc, that don't involve having to watch for changes and such.

**Comment by wclr** [comment]
> Btw, using workspaces doesn't mean you have to incorporate workspaces into a repository and version control. You simply create a local root workspace and clone what you need 

It is just another approach without involving additional tools like yalc.

> I'm trying to figure out use-cases for yalc, that don't involve having to watch for changes and such.

Well if you developing some lib as a separate package it is probably supposed to be self-sufficient. You make some **consistent** changes (e.g. add some functionality), and then push/pull them with yalc. So you have an intermediate step of updating your project(s) here, but it only reflects the nature of those changes that they are consistent. The changes you make to a package, refer first of all to the package, and only secondarily to projects that depend on it.
