### ISSUE TITLE
Can this help for non-published packages ?

### ISSUE THREAD

**Issue by cyrilchapon** [wclr/yalc#96]
Hey,

In here we have a monorepo like this :

```
/ a
/ b (dep: a)
/ usage (dep: a & b)
```

When I say `dep`, I mean it has a **local** dependency (not only for dev purposes).
Nothing is published, everything is local.

We recently switched from npm to yarn.

Yarn by default **installs** local dependencies into `node_modules` of requiring package.
Which is OK for production (this is the intended use).

We're now looking for a way to add sugar during development phase.
We could `yarn link` everything, but :
- it has limitations
- it adds overhead

I that package supposed to be helping for that kind of use ?

**Comment by whitecolor** [comment]
I would use `yarn workspaces`.

**Comment by cyrilchapon** [comment]
@whitecolor thank you 🙂

Actually, Yarn's workspaces forces us to use a "publish-like" syntax :
```
"a": "0.0.1"
```
And actually symlinks packages; which would be OK for dev purposes.

But actually Yarn's workspaces are not suitable for our production environment; because of :
- hoisting (we can disable this, OK)
- symlinking

There is no way (AFAIK) to "avoid symlinking" in Yarn workspaces; and actually do **copy** the files (just like a raw local-package (file://) `yarn install`). You see what I mean ?

To summup :
- if I choose yarn workspace; I have to put `"a": "0.0.1"`. This works in dev, but doesn't work in production (since `a` is not published at all; and Yarns looks into the registry)
- if I choose local packages `"a": "file://../a"`; I'm able to get a production environment; but I'm not able to automatically symlink anymore (except manually symlinking everywhere)

**Comment by whitecolor** [comment]
> But actually Yarn's workspaces are not suitable for our production environment; 

This depends on how you use it, on your build workflow, etc. I use it in production.

Yalc works simple way. Copies to local-repo and grabs from it, that actually all it does.

**Comment by garyo** [comment]
I'm in the same situation as @cyrilchapon . I'm using `yarn workspace` but it doesn't help with production deploy: I use docker and Google Cloud Functions, and both of those expect everything in `package.json` to be findable on the remote side (in Docker's case, in the docker context, which doesn't contain my `a` module). So yarn workspaces are not sufficient for a production workflow like this. I'm hoping `yalc` can do it; if it copies the `a` and `b` modules into the current dir somewhere and sets up package.json to find them there, then the docker build might work (and same for Google Cloud Functions; I think it copies the current dir but not sure).

It will be a multi-step workflow to build and push the `a` module when it changes, so the main module picks up the new version, but perhaps that can't be avoided.

**Comment by whitecolor** [comment]
> in Docker's case, in the docker context, which doesn't contain my a module

So, then the context should contain it.

**Comment by yuvalyacoby** [comment]
@cyrilchapon we are encountering same scenario, curious to know if and how you managed to solve it with `yalc`, or if you used some other solution ?

**Comment by cyrilchapon** [comment]
@yuvalyacoby yes I've been using "yarn workspaces" (which has greatly improved and simplified over time). Give it a try, it's strange at start but definitely worth a look
